# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-08 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clipBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_str', models.IntegerField()),
                ('content', models.TextField(null=True)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
