# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='int_time',
            field=models.IntegerField(default=1481647411),
            preserve_default=False,
        ),
    ]
