# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-13 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_clipboard_int_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='valid_scope',
            field=models.IntegerField(default=300),
        ),
    ]
