# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0003_clipboard_valid_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='expire_date_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
