# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-14 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0004_clipboard_expire_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clipboard',
            name='max_valid_scope',
            field=models.IntegerField(default=7500),
        ),
    ]
